logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event

spring:
  rabbitmq:
    exchange: securities
    routingKeyPrefix: bond
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://eventeum_pre:ioBuilders18@ds125693.mlab.com:25693/eventeum}