server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060

logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

eventFilters:
- id: AlastriaTelsius.TokenMinted
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: Mint
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.TokenBurnt
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: Burn
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.TokenTransferred
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: NativeTransfer
    indexedParameterDefinitions:
    - position: 0
      type: ADDRESS
    - position: 1
      type: ADDRESS
    nonIndexedParameterDefinitions:
    - position: 2
      type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.TransferOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: TransferOrdered
    indexedParameterDefinitions:
      - position: 1
        type: ADDRESS
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.TransferReleased
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: TransferReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.TransferRevoked
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: TransferRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
      - position: 5
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.LogPermissionSet
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_REGULATED_TOKEN:0x1f492a9cc887993a51877a1e5e7455e4e2351f20}
  eventSpecification:
    eventName: LogPermissionSet
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 2
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.RedeemOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: RedeemOrdered
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.RedeemReleased
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: RedeemReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.RedeemRevoked
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x6658d0948929def8b8deb44f2a21a7b5ca6d5b8e}
  eventSpecification:
    eventName: RedeemRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.OTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0xb2b64403869fa9707b6cf30ccce05a896018c23a}
  eventSpecification:
    eventName: OTPRequested
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.OTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0xb2b64403869fa9707b6cf30ccce05a896018c23a}
  eventSpecification:
    eventName: OTPVerificationOrdered
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: UINT256
    nonIndexedParameterDefinitions:
      - position: 2
        type: STRING
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.NewOTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0xb2b64403869fa9707b6cf30ccce05a896018c23a}
  eventSpecification:
    eventName: NewOTPRequested
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.NewOTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0xb2b64403869fa9707b6cf30ccce05a896018c23a}
  eventSpecification:
    eventName: NewOTPVerificationOrdered
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: UINT256
    nonIndexedParameterDefinitions:
     - position: 2
       type: STRING
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: AlastriaTelsius.KycLevelSetToUser
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_COMPLIANCE:0xd3f33245334ce740d95a4e3ecfc6db8c77628174}
  eventSpecification:
    eventName: KycLevelSetToUser
    indexedParameterDefinitions:
    - position: 1
      type: ADDRESS
    nonIndexedParameterDefinitions:
    - position: 0
      type: ADDRESS
    - position: 2
      type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TokenMinted
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: Mint
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TokenBurnt
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: Burn
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TokenTransferred
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: NativeTransfer
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 2
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TransferOrdered
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: TransferOrdered
    indexedParameterDefinitions:
      - position: 1
        type: ADDRESS
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TransferReleased
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: TransferReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.TransferRevoked
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: TransferRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
      - position: 5
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.LogPermissionSet
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_REGULATED_TOKEN_PANTHEON:0xB0320ec72359E9A73e7039Eb2cf94896c7AD8f6a}
  eventSpecification:
    eventName: LogPermissionSet
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 2
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.RedeemOrdered
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: RedeemOrdered
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.RedeemReleased
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: RedeemReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.RedeemRevoked
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN_PANTHEON:0x5F48794Acf980E9e6126bFaB68b2F0d92BEC15f4}
  eventSpecification:
    eventName: RedeemRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.OTPRequested
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_OTP_PANTHEON:0x7F5dEb24aFcA810e571010a1653c16dFFf2B0585}
  eventSpecification:
    eventName: OTPRequested
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.OTPVerificationOrdered
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_OTP_PANTHEON:0x7F5dEb24aFcA810e571010a1653c16dFFf2B0585}
  eventSpecification:
    eventName: OTPVerificationOrdered
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: UINT256
    nonIndexedParameterDefinitions:
      - position: 2
        type: STRING
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.NewOTPRequested
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_OTP_PANTHEON:0x7F5dEb24aFcA810e571010a1653c16dFFf2B0585}
  eventSpecification:
    eventName: NewOTPRequested
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.NewOTPVerificationOrdered
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_OTP_PANTHEON:0x7F5dEb24aFcA810e571010a1653c16dFFf2B0585}
  eventSpecification:
    eventName: NewOTPVerificationOrdered
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: UINT256
    nonIndexedParameterDefinitions:
      - position: 2
        type: STRING
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: Pantheon.KycLevelSetToUser
  node: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
  contractAddress: ${CONTRACT_ADDRESS_COMPLIANCE_PANTHEON:0x82493980B2f8b8332e8e422552244aA9D1dFe063}
  eventSpecification:
    eventName: KycLevelSetToUser
    indexedParameterDefinitions:
      - position: 1
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 2
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event

spring:
  profiles.active: local
  data:
    mongodb:
      uri: mongodb://172.25.0.7:27017/test

ethereum:
  nodes:
  - name: ${ETHEREUM_NETWORK:AlastriaTelsius}
    url: ${ETHEREUM_URL:http://34.241.169.145:22000}
  - name: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
    url: ${ETHEREUM_URL_PANTHEON:https://regular.pre.iosec.io.builders:8565}
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL

broadcaster:
  type: RABBIT
  cache:
    expirationMillis: 6000000
  event:
    confirmation:
      numBlocksToWait: 0
      numBlocksToWaitForMissingTx: 100
  multiInstance: false

rabbitmq:
  exchange: money
  routingKeyPrefix: eventeum
  blockNotification: false

# For Kafka
zookeeper:
  address: ${ZOOKEEPER_ADDRESS:localhost:2181}
kafka:
  bootstrap:
    addresses: ${KAFKA_ADDRESSES:localhost:9092}
  topic:
    contractEvents: contract-events
    blockEvents: block-events
    filterEvents: filter-events

management:
  endpoints:
    web.base-path: /monitoring
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always