logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event

spring:
  rabbitmq:
    host: localhost
    port: 32910
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

ethereum:
  nodes:
  - name: ${ETHEREUM_NETWORK:AlastriaTelsius}
    url: ${ETHEREUM_URL:http://34.241.169.145:22000}
    pollingInterval: 20000
  - name: ${ETHEREUM_NETWORK_PANTHEON:Pantheon}
    url: ${ETHEREUM_URL_PANTHEON:https://regular.pre.iosec.io.builders:8565}
    pollingInterval: 20000
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL