logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event

spring:
  rabbitmq:
    host: ${RABBIT_HOST:bee-01.rmq.cloudamqp.com}
    virtualHost: ${RABBIT_VIRTUALHOST:tyxtiljc}
    username: ${RABBIT_USER:tyxtiljc}
    password: ${RABBIT_PASSWORD:U4Mwzhnake0OL9nh3R1NTCDlvg9sGl1W}
    connectionTimeout: 30000
    port: 5672
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:ioBuilders18@ds133017.mlab.com:33017/eventeum-iocash-prod}

eventFilters:
- id: TokenMinted
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: Mint
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: TokenBurnt
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: Burn
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 1
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: TokenTransferred
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: NativeTransfer
    indexedParameterDefinitions:
    - position: 0
      type: ADDRESS
    - position: 1
      type: ADDRESS
    nonIndexedParameterDefinitions:
    - position: 2
      type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: TransferOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: TransferOrdered
    indexedParameterDefinitions:
      - position: 1
        type: ADDRESS
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: TransferReleased
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: TransferReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: TransferRevoked
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: TransferRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
      - position: 3
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 4
        type: UINT256
      - position: 5
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: LogPermissionSet
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_REGULATED_TOKEN:0xb76ebfedd5d21bc52d31df5ac23a4aff491641c7}
  eventSpecification:
    eventName: LogPermissionSet
    indexedParameterDefinitions:
      - position: 0
        type: ADDRESS
      - position: 1
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 2
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: RedeemOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: RedeemOrdered
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: RedeemReleased
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: RedeemReleased
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: RedeemRevoked
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_EM_TOKEN:0x3dd010d4be66689459d76c792308485a40df3b7e}
  eventSpecification:
    eventName: RedeemRevoked
    indexedParameterDefinitions:
      - position: 2
        type: ADDRESS
    nonIndexedParameterDefinitions:
      - position: 0
        type: STRING
      - position: 1
        type: ADDRESS
      - position: 3
        type: UINT256
      - position: 4
        type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
- id: OTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: OTPRequested
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: OTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: OTPVerificationOrdered
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
     - position: 1
       type: UINT256
   nonIndexedParameterDefinitions:
     - position: 2
       type: STRING
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: NewOTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: NewOTPRequested
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: NewOTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: NewOTPVerificationOrdered
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
     - position: 1
       type: UINT256
   nonIndexedParameterDefinitions:
     - position: 2
       type: STRING
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: OTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: OTPRequested
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: OTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: OTPVerificationOrdered
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
     - position: 1
       type: UINT256
   nonIndexedParameterDefinitions:
     - position: 2
       type: STRING
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: NewOTPRequested
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: NewOTPRequested
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: NewOTPVerificationOrdered
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_OTP:0x8e60522de660aaacf50fefd2ec9199e1d164659d}
  eventSpecification:
   eventName: NewOTPVerificationOrdered
   indexedParameterDefinitions:
     - position: 0
       type: ADDRESS
     - position: 1
       type: UINT256
   nonIndexedParameterDefinitions:
     - position: 2
       type: STRING
  correlationId:
   type: NON_INDEXED_PARAMETER
   index: 0
- id: KycLevelSetToUser
  node: ${ETHEREUM_NETWORK:AlastriaTelsius}
  contractAddress: ${CONTRACT_ADDRESS_COMPLIANCE:0xaa8e1a4bd710903dd5fc1164114a2a9aa0347131}
  eventSpecification:
    eventName: KycLevelSetToUser
    indexedParameterDefinitions:
    - position: 1
      type: ADDRESS
    nonIndexedParameterDefinitions:
    - position: 0
      type: ADDRESS
    - position: 2
      type: UINT8
  correlationId:
    type: NON_INDEXED_PARAMETER
    index: 0
